name: Code Quality

on:
  pull_request:
    branches: [ 'main', 'dev' ]
    types:
      - opened
    paths-ignore:
      - 'docs/**'
  push:
    branches: [ 'main', 'dev' ]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
    if: github.actor != 'dependabot[bot]'

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0
